package com.entity;

public class TDept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.id
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.code
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.name
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.parantid
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    private Integer parantid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.id
     *
     * @return the value of t_dept.id
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.id
     *
     * @param id the value for t_dept.id
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.code
     *
     * @return the value of t_dept.code
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.code
     *
     * @param code the value for t_dept.code
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.name
     *
     * @return the value of t_dept.name
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.name
     *
     * @param name the value for t_dept.name
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.parantid
     *
     * @return the value of t_dept.parantid
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    public Integer getParantid() {
        return parantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.parantid
     *
     * @param parantid the value for t_dept.parantid
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    public void setParantid(Integer parantid) {
        this.parantid = parantid;
    }
}