package com.dao;

import com.entity.TDept;

public interface TDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int insert(TDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int insertSelective(TDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    TDept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int updateByPrimaryKeySelective(TDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int updateByPrimaryKey(TDept record);
}