package com.dao;

import java.util.List;

import com.entity.TPermission;

public interface TPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int insert(TPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int insertSelective(TPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    TPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int updateByPrimaryKeySelective(TPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int updateByPrimaryKey(TPermission record);
    //通过角色id查权限
    List<TPermission> findAllMenu(int rid);
    //通过用户名查权限
    List<TPermission> findPermissionByName(int uid);
}