package com.dao;

import java.util.HashSet;
import java.util.Set;

import com.entity.TRole;
import com.entity.TUser;

public interface TRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int insert(TRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int insertSelective(TRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    TRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int updateByPrimaryKeySelective(TRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int updateByPrimaryKey(TRole record);
    Set<TRole> findRolesByUserId(int id);
}