package com.dao;

import com.entity.TUserRole;

public interface TUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int insert(TUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Mon Jan 28 16:04:07 CST 2019
     */
    int insertSelective(TUserRole record);
}